# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - type:ci
    # https://til.simonwillison.net/github/dependabot-python-setup
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    labels:
      - type:dependency
    versioning-strategy: increase-if-necessary
    ignore:
      # https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/92
      - dependency-name: towncrier
      - dependency-name: pytest-asyncio
        update-types: [version-update:semver-major]
    # https://til.simonwillison.net/github/dependabot-python-setup
    groups:
      python-packages:
        patterns:
          - '*'
