default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
        types: [python]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
      - id: remove-tabs
        args: [--whitespaces-count, '2']
      - id: chmod
        args: ['644']
        exclude_types: [shell]
        exclude: ^(.*__main__\.py|data_rentgen/server/scripts/.*\.py|data_rentgen/db/scripts/[^/]+\.py|data_rentgen/http2kafka/scripts/.*\.py)$
      - id: chmod
        args: ['755']
        files: ^(.*__main__\.py|data_rentgen/server/scripts/.*\.py|data_rentgen/db/scripts/[^/]+\.py|data_rentgen/http2kafka/scripts/.*\.py)$
      - id: insert-license
        files: .*\.py$
        exclude: ^(data_rentgen/dependencies/stub.py|docs/.*\.py|tests/.*\.py)$
        args:
          - --license-filepath
          - .spdx-license-header.txt
          - --allow-past-years
          - --no-extra-eol

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus, --keep-runtime-typing]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-w]
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.19
    hooks:
      - id: uv-lock
        args: [--prerelease=allow]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy ./data_rentgen --config-file ./pyproject.toml
        language: python
        types: [python]
        require_serial: true
        pass_filenames: false

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

ci:
  skip:
    - mypy # checked with Github Actions
    - docker-compose-check # cannot run on pre-commit.ci
    - chmod # failing in pre-commit.ci
    - uv-lock # failing in pre-commit.ci in cause of https://github.com/astral-sh/uv/issues/10167
