version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - autoconf
    - make
    - gcc
  tools:
    python: '3.13'
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - python -m pip install poetry
      - python -m pip install --no-deps sphinx-plantuml # remove after https://github.com/zqmillet/sphinx-plantuml/pull/4
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry debug info
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install --no-root --extras server --extras consumer --with docs --without dev,test
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry show -v
      - python -m pip list -v
      - make openapi

sphinx:
  configuration: docs/conf.py
