services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3

  broker:
    image: bitnami/kafka:3.9
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 9093:9093
    volumes:
      - kafka_test_data:/bitnami/kafka
    healthcheck:
      test: [CMD-SHELL, kafka-topics.sh --bootstrap-server 127.0.0.1:9095 --list]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - consumer
      - all

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
    profiles:
      - keycloak
      - all

volumes:
  postgres_test_data:
  kafka_test_data:
  keycloak_data:
