services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3

  broker:
    image: bitnami/kafka:3.7
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 9093:9093
    volumes:
      - kafka_test_data:/bitnami/kafka
    healthcheck:
      test: [CMD-SHELL, kafka-topics.sh --bootstrap-server 127.0.0.1:9095 --list]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
  kafka_test_data:
